import type { Brand, Collection, Product, ProductCategory } from "@rawnaq/types"

// Authentic beauty, cosmetics, fragrance, skincare & electronics catalog sourced directly from roseberryksa.com
export const mockCategories: ProductCategory[] = [
  {
    "id": "c-skincare",
    "name": "العناية بالبشرة",
    "slug": "skincare",
    "parentId": null,
    "level": 1,
    "sortOrder": 1,
    "image": "/images/categories/skincare.webp"
  },
  {
    "id": "c-makeup",
    "name": "المكياج والتجميل",
    "slug": "makeup",
    "parentId": null,
    "level": 1,
    "sortOrder": 2,
    "image": "/images/categories/makeup.webp"
  },
  {
    "id": "c-boxes",
    "name": "بوكسات وهدايا التجميل",
    "slug": "boxes-bundles",
    "parentId": null,
    "level": 1,
    "sortOrder": 3,
    "image": "/images/categories/boxes.webp"
  },
  {
    "id": "c-fragrance",
    "name": "العطور والمسك الفاخر",
    "slug": "fragrance",
    "parentId": null,
    "level": 1,
    "sortOrder": 4,
    "image": "/images/categories/fragrance.webp"
  },
  {
    "id": "c-hair",
    "name": "العناية بالشعر",
    "slug": "hair-care",
    "parentId": null,
    "level": 1,
    "sortOrder": 5,
    "image": "/images/categories/haircare.webp"
  },
  {
    "id": "c-body",
    "name": "بودرة وعناية الجسم",
    "slug": "body-care",
    "parentId": null,
    "level": 1,
    "sortOrder": 6,
    "image": "/images/categories/bodycare.webp"
  },
  {
    "id": "c-electronics",
    "name": "أجهزة التجميل والعناية",
    "slug": "electronics",
    "parentId": null,
    "level": 1,
    "sortOrder": 7,
    "image": "/images/categories/electronics.webp"
  },
  {
    "id": "c-summer",
    "name": "روتين الصيف والنضارة",
    "slug": "summer-routine",
    "parentId": null,
    "level": 1,
    "sortOrder": 8,
    "image": "/images/categories/summer.webp"
  },
  {
    "id": "c-deals",
    "name": "عروض وتخفيضات حصرية",
    "slug": "deals",
    "parentId": null,
    "level": 1,
    "sortOrder": 9,
    "image": "/images/categories/offers.webp"
  },
  {
    "id": "c-face",
    "name": "مكياج الوجه والأساس",
    "slug": "face-makeup",
    "parentId": "c-makeup",
    "level": 2,
    "sortOrder": 1
  },
  {
    "id": "c-eyes",
    "name": "مكياج وظلال العيون",
    "slug": "eye-makeup",
    "parentId": "c-makeup",
    "level": 2,
    "sortOrder": 2
  },
  {
    "id": "c-lips",
    "name": "أحمر وملمع الشفاه",
    "slug": "lip-makeup",
    "parentId": "c-makeup",
    "level": 2,
    "sortOrder": 3
  },
  {
    "id": "c-hair-mists",
    "name": "معطرات ومخمريات الشعر",
    "slug": "hair-mists",
    "parentId": "c-hair",
    "level": 2,
    "sortOrder": 1
  },
  {
    "id": "c-musk",
    "name": "مسك الطهارة والمسك الفاخر",
    "slug": "musk",
    "parentId": "c-fragrance",
    "level": 2,
    "sortOrder": 1
  },
  {
    "id": "c-body-powders",
    "name": "بودرات الجسم المعطرة",
    "slug": "body-powders",
    "parentId": "c-body",
    "level": 2,
    "sortOrder": 1
  },
  {
    "id": "c-hair-tools",
    "name": "أجهزة ومصففات الشعر",
    "slug": "hair-stylers",
    "parentId": "c-electronics",
    "level": 2,
    "sortOrder": 1
  },
  {
    "id": "c-skin-devices",
    "name": "أجهزة تنظيف وشد البشرة",
    "slug": "facial-devices",
    "parentId": "c-electronics",
    "level": 2,
    "sortOrder": 2
  }
]

export const mockBrands: Brand[] = [
  {
    "id": "b-roseberry",
    "slug": "roseberry",
    "name": "روز بيري - Roseberry",
    "description": "علامة رائدة وموثوقة تقدم أفخم مستحضرات التجميل والعناية بتركيبات استثنائية.",
    "logo": "/images/brands/roseberry.jpg",
    "image": "/images/brands/roseberry.jpg",
    "productImage": "/images/brands/roseberry.jpg",
    "featured": true
  },
  {
    "id": "b-golf-orchid",
    "slug": "golf-orchid",
    "name": "جولف أوركيد - Gulf Orchid",
    "description": "تأسست عام 1987 وتقدم أرقى العطور، مسك الطهارة، ومعطرات الشعر الفاخرة.",
    "logo": "/images/brands/golf-orchid.jpg",
    "image": "/images/brands/golf-orchid.jpg",
    "productImage": "/images/brands/golf-orchid.jpg",
    "featured": true
  },
  {
    "id": "b-heila-beauty",
    "slug": "heila-beauty",
    "name": "هيله بيوتي - Heila Beauty",
    "description": "أطقم مسك راقية وبوكسات إهداء تليق بكل المناسبات.",
    "logo": "/images/brands/heila-beauty.jpg",
    "image": "/images/brands/heila-beauty.jpg",
    "productImage": "/images/brands/heila-beauty.jpg",
    "featured": true
  },
  {
    "id": "b-magic-skin",
    "slug": "magic-skin",
    "name": "ماجيك سكين - Magic Skin",
    "description": "حلول مبتكرة للعناية الفائقة وزيوت الجسم وأجهزة البشرة العصرية.",
    "logo": "/images/brands/magic-skin.png",
    "image": "/images/brands/magic-skin.png",
    "productImage": "/images/brands/magic-skin.png",
    "featured": true
  },
  {
    "id": "b-y-herb",
    "slug": "y-herb",
    "name": "واي هيرب - Y-Herb",
    "description": "منتجات العناية الطبيعية المستخلصة من أنقى المكونات العشبية.",
    "logo": "/images/brands/y-herb.png",
    "image": "/images/brands/y-herb.png",
    "productImage": "/images/brands/y-herb.png",
    "featured": true
  },
  {
    "id": "b-otory",
    "slug": "otory",
    "name": "عطري - Otory",
    "description": "أصالة العطور الشرقية والمخمريات الملكية الفواحة.",
    "logo": "/images/brands/otory.jpg",
    "image": "/images/brands/otory.jpg",
    "productImage": "/images/brands/otory.jpg",
    "featured": true
  },
  {
    "id": "b-memwa",
    "slug": "memwa",
    "name": "ميموا - Memwa",
    "description": "عطور وتوليفات ساحرة تناسب الذوق الرفيع.",
    "logo": "/images/brands/memwa.png",
    "image": "/images/brands/memwa.png",
    "productImage": "/images/brands/memwa.png",
    "featured": false
  },
  {
    "id": "b-bessan-beauty",
    "slug": "bessan-beauty",
    "name": "بيسان بيوتي - Bessan Beauty",
    "description": "مستحضرات عناية وتجميل عصرية تناسب كل يوم.",
    "logo": "/images/brands/bessan-beauty.png",
    "image": "/images/brands/bessan-beauty.png",
    "productImage": "/images/brands/bessan-beauty.png",
    "featured": false
  },
  {
    "id": "b-maison-asrar",
    "slug": "maison-asrar",
    "name": "ميزون أسرار - Maison Asrar",
    "description": "عطور إماراتية فاخرة بمكونات أصيلة وتوليفات نيش فريدة.",
    "logo": "/images/brands/maison-asrar.jpg",
    "image": "/images/brands/maison-asrar.jpg",
    "productImage": "/images/brands/maison-asrar.jpg",
    "featured": false
  },
  {
    "id": "b-barabora",
    "slug": "barabora",
    "name": "بارابورا - Barabora",
    "description": "أحدث منتجات التجميل ومستحضرات الإطلالة العصرية.",
    "logo": "/images/brands/barabora.png",
    "image": "/images/brands/barabora.png",
    "productImage": "/images/brands/barabora.png",
    "featured": false
  }
]

function category(id: string): ProductCategory {
  const found = mockCategories.find((c) => c.id === id)
  if (!found) {
    throw new Error(`Unknown mock category id: ${id}`)
  }
  return found
}

export const mockProducts: Product[] = [
  {
    id: "rb-1",
    slug: "golf-orchid-hair-mist-luxury-box",
    name: "مجموعة عطور الشعر من جولف أوركيد - 4 عطور",
    subtitle: "الأكثر مبيعاً • جودة معتمدة وتركيبة أصلية 100%",
    description: "رائحة مختلفة لكل مزاج وإطلالة. عطور للشعر ضمن مجموعة جولف أوركيد تمنحكِ 4 خيارات عطرية بحجم عملي، لتختاري كل مرة النفحة التي تكمل حضوركِ.بيانات المجموعةالنوع: م...",
    badges: ["الأكثر مبيعاً"],
    price: {"amount":9.8,"currency":"OMR","compareAtAmount":13.2},
    images: [{"url":"/images/products/rb-1-g1.png","alt":"مجموعة عطور الشعر من جولف أوركيد - 4 عطور - صورة 1"},{"url":"/images/products/rb-1-g2.png","alt":"مجموعة عطور الشعر من جولف أوركيد - 4 عطور - صورة 2"},{"url":"/images/products/rb-1-g3.png","alt":"مجموعة عطور الشعر من جولف أوركيد - 4 عطور - صورة 3"}],
    categories: [category("c-boxes")],
    brandId: "b-golf-orchid",
    rating: {"average":4.8,"count":206},
    inStock: true,
    stockCount: 91
  },
  {
    id: "rb-2",
    slug: "roseberry-liquid-lip-and-cheek-tint-set",
    name: "طقم مورد خدود وشفايف سائل وثابت من روز بيري",
    subtitle: "عرض خاص • جودة معتمدة وتركيبة أصلية 100%",
    description: "تألقي بمظهر جذاب وطبيعي مع طقم مورد خدود وشفايف سائل وثابت من روز بيري. هذا الطقم المثالي يمنحك لونًا مشرقًا وثباتًا يدوم طوال اليوم.امنحي خدودك وشفائك لون متنا...",
    badges: ["عرض خاص"],
    price: {"amount":0.8,"currency":"OMR","compareAtAmount":3.6},
    images: [{"url":"/images/products/rb-2-g1.jpg","alt":"طقم مورد خدود وشفايف سائل وثابت من روز بيري - صورة 1"},{"url":"/images/products/rb-2-g2.jpg","alt":"طقم مورد خدود وشفايف سائل وثابت من روز بيري - صورة 2"},{"url":"/images/products/rb-2-g3.png","alt":"طقم مورد خدود وشفايف سائل وثابت من روز بيري - صورة 3"}],
    categories: [category("c-makeup")],
    brandId: "b-roseberry",
    rating: {"average":4.8999999999999995,"count":117},
    inStock: true,
    stockCount: 80
  },
  {
    id: "rb-3",
    slug: "double-duty-beauty-concealer-roseberry",
    name: "كونسيلر دبل ديوتي بيوتي 10 مل من روز بيري",
    subtitle: "ترند تيك توك • جودة معتمدة وتركيبة أصلية 100%",
    description: "البشرة الصافية والمشرقة هي أساس كل مكياج ناجح وإطلالة مفعمة بالثقة. ولكن، كثيراً ما تقف الهالات السوداء، البقع الداكنة، أو آثار الإرهاق عائقاً أمام الحصول على ذ...",
    badges: ["ترند تيك توك"],
    price: {"amount":1.9,"currency":"OMR","compareAtAmount":2.9},
    images: [{"url":"/images/products/rb-3-g1.jpg","alt":"كونسيلر دبل ديوتي بيوتي 10 مل من روز بيري - صورة 1"},{"url":"/images/products/rb-3-g2.jpg","alt":"كونسيلر دبل ديوتي بيوتي 10 مل من روز بيري - صورة 2"},{"url":"/images/products/rb-3-g3.png","alt":"كونسيلر دبل ديوتي بيوتي 10 مل من روز بيري - صورة 3"}],
    categories: [category("c-makeup")],
    brandId: "b-roseberry",
    rating: {"average":4,"count":2},
    inStock: true,
    stockCount: 56
  },
  {
    id: "rb-4",
    slug: "eyeshadow-palette-24-colors-roseberry",
    name: "باليت أظلال العيون لإطلالات السهرات 24 لون من روز بيري",
    subtitle: "ألوان صيفية • جودة معتمدة وتركيبة أصلية 100%",
    description: "استكشفي عالم من الألوان الغنية باليت ظلال العيون​ Rose Berry. تجمع&nbsp;بين 24 درجة لونية مذهلة، تتنوع ما بين الألوان المات الهادئة، والدرجات اللامعة (Shimmer)،...",
    badges: ["ألوان صيفية"],
    price: {"amount":0.8,"currency":"OMR","compareAtAmount":5.6},
    images: [{"url":"/images/products/rb-4-g1.jpg","alt":"باليت أظلال العيون لإطلالات السهرات 24 لون من روز بيري - صورة 1"},{"url":"/images/products/rb-4-g2.jpg","alt":"باليت أظلال العيون لإطلالات السهرات 24 لون من روز بيري - صورة 2"},{"url":"/images/products/rb-4-g3.png","alt":"باليت أظلال العيون لإطلالات السهرات 24 لون من روز بيري - صورة 3"}],
    categories: [category("c-makeup")],
    brandId: "b-roseberry",
    rating: {"average":4.7,"count":3},
    inStock: true,
    stockCount: 41
  },
  {
    id: "rb-5",
    slug: "eyeshadow-palette-15-colors-roseberry",
    name: "باليت ظل للعيون 15 لون من روز بيري",
    subtitle: "جديد • جودة معتمدة وتركيبة أصلية 100%",
    description: "ودعي تكرار نفس اللوك. مع باليت روز بيري تحصلين على 15 درجة تساعدكِ على التنويع بين إطلالات عيون هادئة، دافئة أو أكثر جرأة حسب مزاجكِ.بيانات الباليت:النوع: باليت...",
    badges: ["جديد"],
    price: {"amount":0.7,"currency":"OMR","compareAtAmount":4},
    images: [{"url":"/images/products/rb-5-g1.jpg","alt":"باليت ظل للعيون 15 لون من روز بيري - صورة 1"},{"url":"/images/products/rb-5-g2.jpg","alt":"باليت ظل للعيون 15 لون من روز بيري - صورة 2"},{"url":"/images/products/rb-5-g3.png","alt":"باليت ظل للعيون 15 لون من روز بيري - صورة 3"}],
    categories: [category("c-makeup")],
    brandId: "b-roseberry",
    rating: {"average":4.8999999999999995,"count":201},
    inStock: true,
    stockCount: 71
  },
  {
    id: "rb-6",
    slug: "roseberry-spf-protective-foundation",
    name: "احصلي على كريم الأساس مع نسبة حماية ضد أشعة الشمس من متجر روز بيري الرسمي في السعودية",
    subtitle: "حماية SPF • جودة معتمدة وتركيبة أصلية 100%",
    description: "احصلي على كريم الأساس مع نسبة حماية ضد أشعة الشمس من متجر روز بيري الرسمي في السعودية من أرقى منتجات الجمال المصممة بأعلى معايير الجودة لتمنحكِ إطلالة ساحرة وعناية متكاملة تدوم طويلاً.",
    badges: ["حماية SPF"],
    price: {"amount":3.9,"currency":"OMR","compareAtAmount":5},
    images: [{"url":"/images/products/rb-6-g1.png","alt":"احصلي على كريم الأساس مع نسبة حماية ضد أشعة الشمس من متجر روز بيري الرسمي في السعودية - صورة 1"},{"url":"/images/products/rb-6-g2.png","alt":"احصلي على كريم الأساس مع نسبة حماية ضد أشعة الشمس من متجر روز بيري الرسمي في السعودية - صورة 2"},{"url":"/images/products/rb-6-g3.webp","alt":"احصلي على كريم الأساس مع نسبة حماية ضد أشعة الشمس من متجر روز بيري الرسمي في السعودية - صورة 3"}],
    categories: [category("c-makeup")],
    brandId: "b-roseberry",
    rating: {"average":4.8999999999999995,"count":88},
    inStock: true,
    stockCount: 92
  },
  {
    id: "rb-7",
    slug: "makeup-setting-spray-roseberry",
    name: "بخاخ مثبت مكياج من روزي بيري",
    subtitle: "ثبات 24 ساعة • جودة معتمدة وتركيبة أصلية 100%",
    description: "تبحث كل امرأة عن سر الحفاظ على نضارة وجاذبية مظهرها طوال اليوم دون أن يتأثر بالعوامل الخارجية كالحرارة أو الرطوبة. إذا كنتِ ترغبين في قفل مكياجكِ وثباته لساعات...",
    badges: ["ثبات 24 ساعة"],
    price: {"amount":2,"currency":"OMR","compareAtAmount":3},
    images: [{"url":"/images/products/rb-7-g1.jpg","alt":"بخاخ مثبت مكياج من روزي بيري - صورة 1"},{"url":"/images/products/rb-7-g2.jpg","alt":"بخاخ مثبت مكياج من روزي بيري - صورة 2"},{"url":"/images/products/rb-7-g3.png","alt":"بخاخ مثبت مكياج من روزي بيري - صورة 3"}],
    categories: [category("c-makeup")],
    brandId: "b-roseberry",
    rating: {"average":4.8,"count":349},
    inStock: true,
    stockCount: 43
  },
  {
    id: "rb-8",
    slug: "matte-primer-gel-roseberry",
    name: "برايمر جل مطفي وناعم من روزبيري – أساس مثالي لمكياج يدوم طويلًا",
    subtitle: "مات مطفي • جودة معتمدة وتركيبة أصلية 100%",
    description: "إذا كنتِ تحلمين بإخفاء المسام الواسعة والتحكم في لمعان البشرة المزعج، فإن برايمر روز بيري بتركيبته الهلامية (Gel) المتطورة هو السر الذي تبحثين عنه. برايمر روز ب...",
    badges: ["مات مطفي"],
    price: {"amount":2,"currency":"OMR","compareAtAmount":2.9},
    images: [{"url":"/images/products/rb-8-g1.jpg","alt":"برايمر جل مطفي وناعم من روزبيري – أساس مثالي لمكياج يدوم طويلًا - صورة 1"},{"url":"/images/products/rb-8-g2.jpg","alt":"برايمر جل مطفي وناعم من روزبيري – أساس مثالي لمكياج يدوم طويلًا - صورة 2"},{"url":"/images/products/rb-8-g3.png","alt":"برايمر جل مطفي وناعم من روزبيري – أساس مثالي لمكياج يدوم طويلًا - صورة 3"}],
    categories: [category("c-makeup")],
    brandId: "b-roseberry",
    rating: {"average":4.8999999999999995,"count":133},
    inStock: true,
    stockCount: 50
  },
  {
    id: "rb-9",
    slug: "natural-horse-hair-lashes-roseberry",
    name: "رموش شعر الحصان من روزبيري",
    subtitle: "طبيعي 100% • جودة معتمدة وتركيبة أصلية 100%",
    description: "رموش شعر الحصان من روزبيري من أرقى منتجات الجمال المصممة بأعلى معايير الجودة لتمنحكِ إطلالة ساحرة وعناية متكاملة تدوم طويلاً.",
    badges: ["طبيعي 100%"],
    price: {"amount":1.5,"currency":"OMR","compareAtAmount":2.2},
    images: [{"url":"/images/products/rb-9-g1.png","alt":"رموش شعر الحصان من روزبيري - صورة 1"},{"url":"/images/products/rb-9-g2.png","alt":"رموش شعر الحصان من روزبيري - صورة 2"},{"url":"/images/products/rb-9-g3.webp","alt":"رموش شعر الحصان من روزبيري - صورة 3"}],
    categories: [category("c-makeup")],
    brandId: "b-roseberry",
    rating: {"average":4.8999999999999995,"count":328},
    inStock: true,
    stockCount: 89
  },
  {
    id: "rb-10",
    slug: "magic-lip-and-cheek-tint-roseberry",
    name: "مورد خدود وشفايف سحري 30 مل من روز بيري",
    subtitle: "وردي طبيعي • جودة معتمدة وتركيبة أصلية 100%",
    description: "هل تبحثين عن لمسة حيوية تدوم معكِ طوال اليوم؟ اكتشفي مورد الخدود والشفايف السحري من روز بيري. بتركيبة فريدة تندمج مع بشرتكِ لتمنحكِ لون وردي طبيعي وكأنكِ لا تضع...",
    badges: ["وردي طبيعي"],
    price: {"amount":1.2,"currency":"OMR","compareAtAmount":1.8},
    images: [{"url":"/images/products/rb-10-g1.jpg","alt":"مورد خدود وشفايف سحري 30 مل من روز بيري - صورة 1"},{"url":"/images/products/rb-10-g2.jpg","alt":"مورد خدود وشفايف سحري 30 مل من روز بيري - صورة 2"},{"url":"/images/products/rb-10-g3.png","alt":"مورد خدود وشفايف سحري 30 مل من روز بيري - صورة 3"}],
    categories: [category("c-makeup")],
    brandId: "b-roseberry",
    rating: {"average":5,"count":2},
    inStock: true,
    stockCount: 88
  },
  {
    id: "rb-11",
    slug: "clear-lip-gloss-roseberry",
    name: "ليب جلاس شفاف",
    subtitle: "لمعان زجاجي • جودة معتمدة وتركيبة أصلية 100%",
    description: "ليب جلاس شفاف من أرقى منتجات الجمال المصممة بأعلى معايير الجودة لتمنحكِ إطلالة ساحرة وعناية متكاملة تدوم طويلاً.",
    badges: ["لمعان زجاجي"],
    price: {"amount":1.2,"currency":"OMR","compareAtAmount":1.7},
    images: [{"url":"/images/products/rb-11-g1.png","alt":"ليب جلاس شفاف - صورة 1"},{"url":"/images/products/rb-11-g2.png","alt":"ليب جلاس شفاف - صورة 2"},{"url":"/images/products/rb-11-g3.webp","alt":"ليب جلاس شفاف - صورة 3"}],
    categories: [category("c-makeup")],
    brandId: "b-roseberry",
    rating: {"average":4.8999999999999995,"count":103},
    inStock: true,
    stockCount: 30
  },
  {
    id: "rb-12",
    slug: "bravo-perfume-30ml-roseberry",
    name: "عطر برافو من روز بيري - 30 مل",
    subtitle: "فاخر • جودة معتمدة وتركيبة أصلية 100%",
    description: "عطر برافو خيار مثالي للصيف والربيع يمنحك انتعاش صباحي وثبات يرافقك طوال اليوم بإحساس منعش وجذاب ومناسب للصباح اليومي.مواصفات عطر برافوالنوع: عطر.الماركة: روز بي...",
    badges: ["فاخر"],
    price: {"amount":1.2,"currency":"OMR","compareAtAmount":3.6},
    images: [{"url":"/images/products/rb-12-g1.jpg","alt":"عطر برافو من روز بيري - 30 مل - صورة 1"},{"url":"/images/products/rb-12-g2.jpg","alt":"عطر برافو من روز بيري - 30 مل - صورة 2"},{"url":"/images/products/rb-12-g3.png","alt":"عطر برافو من روز بيري - 30 مل - صورة 3"}],
    categories: [category("c-fragrance")],
    brandId: "b-roseberry",
    rating: {"average":5,"count":1},
    inStock: true,
    stockCount: 46
  },
  {
    id: "rb-13",
    slug: "dark-women-perfume-30ml-roseberry",
    name: "عطر دارك نسائي من روز بيري - 30 مل",
    subtitle: "أنيق وجذاب • جودة معتمدة وتركيبة أصلية 100%",
    description: "عطر يجمع بين الانتعاش والدفء في رائحة واحدة، يبدأ بنفحات منعشة ثم يتحول تدريجيًا إلى طابع خشبي حلو يمنحك حضور ثابت وإحساس بالثقة.مواصفات عطر دارك نسائيالنوع: عط...",
    badges: ["أنيق وجذاب"],
    price: {"amount":1.2,"currency":"OMR","compareAtAmount":3.6},
    images: [{"url":"/images/products/rb-13-g1.jpg","alt":"عطر دارك نسائي من روز بيري - 30 مل - صورة 1"},{"url":"/images/products/rb-13-g2.jpg","alt":"عطر دارك نسائي من روز بيري - 30 مل - صورة 2"},{"url":"/images/products/rb-13-g3.png","alt":"عطر دارك نسائي من روز بيري - 30 مل - صورة 3"}],
    categories: [category("c-fragrance")],
    brandId: "b-roseberry",
    rating: {"average":4.8,"count":356},
    inStock: true,
    stockCount: 42
  },
  {
    id: "rb-14",
    slug: "fahrenheit-mini-perfume-golf-orchid",
    name: "عطر ميني برائحة فهرنهايت من جولف أوركيد  - 30 مل",
    subtitle: "ثبات عالي • جودة معتمدة وتركيبة أصلية 100%",
    description: "عطر فهرنهايت من جولف اوركيد يجمع بين الحمضيات والتوابل والجلود ليمنحك رائحة قوية دافئة جذابة تعكس شخصية واثقة وتبقى ثابتة طوال اليوم مميزة.مواصفات عطر فهرنهايتا...",
    badges: ["ثبات عالي"],
    price: {"amount":1.2,"currency":"OMR","compareAtAmount":11.2},
    images: [{"url":"/images/products/rb-14-g1.jpg","alt":"عطر ميني برائحة فهرنهايت من جولف أوركيد  - 30 مل - صورة 1"},{"url":"/images/products/rb-14-g2.jpg","alt":"عطر ميني برائحة فهرنهايت من جولف أوركيد  - 30 مل - صورة 2"},{"url":"/images/products/rb-14-g3.png","alt":"عطر ميني برائحة فهرنهايت من جولف أوركيد  - 30 مل - صورة 3"}],
    categories: [category("c-fragrance")],
    brandId: "b-golf-orchid",
    rating: {"average":4.8999999999999995,"count":167},
    inStock: true,
    stockCount: 60
  },
  {
    id: "rb-15",
    slug: "sun-rise-mini-perfume-golf-orchid",
    name: "عطر ميني برائحة اسكادا سان سيت 30 مل",
    subtitle: "رائحة منعشة • جودة معتمدة وتركيبة أصلية 100%",
    description: "عطر ميني برائحة اسكادا سان سيت من جولف أوركيد يمنحك انتعاش صيفي ناعم ولمسة أنثوية ساحرة تدوم طوال اليوم.مواصفات عطر اسكادا سان سيتالنوع: عطر.الماركة: روز بيرى.ا...",
    badges: ["رائحة منعشة"],
    price: {"amount":1.2,"currency":"OMR","compareAtAmount":11.2},
    images: [{"url":"/images/products/rb-15-g1.jpg","alt":"عطر ميني برائحة اسكادا سان سيت 30 مل - صورة 1"},{"url":"/images/products/rb-15-g2.jpg","alt":"عطر ميني برائحة اسكادا سان سيت 30 مل - صورة 2"},{"url":"/images/products/rb-15-g3.png","alt":"عطر ميني برائحة اسكادا سان سيت 30 مل - صورة 3"}],
    categories: [category("c-fragrance")],
    brandId: "b-golf-orchid",
    rating: {"average":4.8999999999999995,"count":97},
    inStock: true,
    stockCount: 48
  },
  {
    id: "rb-16",
    slug: "arabic-rose-perfume-golf-orchid",
    name: "عطر ميني برائحة أرب روز ارماني 30 مل للرجال",
    subtitle: "دهن الورد • جودة معتمدة وتركيبة أصلية 100%",
    description: "اكتشف عطر ميني أرب روز ارماني 30 مل للرجال افضل عطر ميمو من جولف أوركيد برائحة جذابة تعكس الأناقة والثبات يبحث عنه عشاق التميز.مواصفات عطر ميني :النوع: عطر.الما...",
    badges: ["دهن الورد"],
    price: {"amount":1.2,"currency":"OMR","compareAtAmount":11.7},
    images: [{"url":"/images/products/rb-16-g1.jpg","alt":"عطر ميني برائحة أرب روز ارماني 30 مل للرجال - صورة 1"},{"url":"/images/products/rb-16-g2.jpg","alt":"عطر ميني برائحة أرب روز ارماني 30 مل للرجال - صورة 2"},{"url":"/images/products/rb-16-g3.png","alt":"عطر ميني برائحة أرب روز ارماني 30 مل للرجال - صورة 3"}],
    categories: [category("c-fragrance")],
    brandId: "b-golf-orchid",
    rating: {"average":4.8999999999999995,"count":280},
    inStock: true,
    stockCount: 76
  },
  {
    id: "rb-17",
    slug: "hero-men-perfume-golf-orchid",
    name: "عطر ميني برائحة ذا سنت  30 مل رجالي",
    subtitle: "رجالي مميز • جودة معتمدة وتركيبة أصلية 100%",
    description: "اكتشف عطر ذا سنت الذي يمنحك حضور إحساس منعش يدوم ويعكس ذوقك الراقي في كل لحظة من يومك مع لمسة عطرية جذابة.مواصفات عطر ذا سنتالنوع: عطر.الماركة: روز بيرى.الحجم:...",
    badges: ["رجالي مميز"],
    price: {"amount":1.2,"currency":"OMR","compareAtAmount":12.2},
    images: [{"url":"/images/products/rb-17-g1.jpg","alt":"عطر ميني برائحة ذا سنت  30 مل رجالي - صورة 1"},{"url":"/images/products/rb-17-g2.jpg","alt":"عطر ميني برائحة ذا سنت  30 مل رجالي - صورة 2"},{"url":"/images/products/rb-17-g3.png","alt":"عطر ميني برائحة ذا سنت  30 مل رجالي - صورة 3"}],
    categories: [category("c-fragrance")],
    brandId: "b-golf-orchid",
    rating: {"average":4.8,"count":194},
    inStock: true,
    stockCount: 86
  },
  {
    id: "rb-18",
    slug: "dark-xs-eau-de-toilette-roseberry",
    name: "عطر ميني برائحة باكو رابان بلاك اكس اس 30 مل من ميموا جولف أوركيد",
    subtitle: "تواليت فاخر • جودة معتمدة وتركيبة أصلية 100%",
    description: "اكتشف عطر بلاك اكس باكو رابان بلاك اكس اس برائحة جذابة دافئة تمزج الفانيليا والتوابل والخشب لتمنحك حضورًا لا يُنسى طوال الوقت الجذاب.مواصفات عطر بلاك اكس باكو ر...",
    badges: ["تواليت فاخر"],
    price: {"amount":1.2,"currency":"OMR","compareAtAmount":5.6},
    images: [{"url":"/images/products/rb-18-g1.jpg","alt":"عطر ميني برائحة باكو رابان بلاك اكس اس 30 مل من ميموا جولف أوركيد - صورة 1"},{"url":"/images/products/rb-18-g2.jpg","alt":"عطر ميني برائحة باكو رابان بلاك اكس اس 30 مل من ميموا جولف أوركيد - صورة 2"},{"url":"/images/products/rb-18-g3.png","alt":"عطر ميني برائحة باكو رابان بلاك اكس اس 30 مل من ميموا جولف أوركيد - صورة 3"}],
    categories: [category("c-fragrance")],
    brandId: "b-roseberry",
    rating: {"average":4.8999999999999995,"count":188},
    inStock: true,
    stockCount: 80
  },
  {
    id: "rb-19",
    slug: "mr-vip-eau-de-toilette-roseberry",
    name: "عطر ميني برائحة عطر كارولينا هيريرا 212 في آي بي 30 مل من ميموا جولف أوركيد",
    subtitle: "VIP عطر • جودة معتمدة وتركيبة أصلية 100%",
    description: "اكتشف عطر كارولينا هيريرا رجالي برائحة كارولينا هيريرا 212 في آي بي من ميموا جولف أوركيد يجمع بين الفخامة والانتعاش والجاذبية للرجال العصريين مع ثبات عالي.مواصف...",
    badges: ["VIP عطر"],
    price: {"amount":1.2,"currency":"OMR","compareAtAmount":5.6},
    images: [{"url":"/images/products/rb-19-g1.jpg","alt":"عطر ميني برائحة عطر كارولينا هيريرا 212 في آي بي 30 مل من ميموا جولف أوركيد - صورة 1"},{"url":"/images/products/rb-19-g2.jpg","alt":"عطر ميني برائحة عطر كارولينا هيريرا 212 في آي بي 30 مل من ميموا جولف أوركيد - صورة 2"},{"url":"/images/products/rb-19-g3.png","alt":"عطر ميني برائحة عطر كارولينا هيريرا 212 في آي بي 30 مل من ميموا جولف أوركيد - صورة 3"}],
    categories: [category("c-fragrance")],
    brandId: "b-roseberry",
    rating: {"average":4.5,"count":2},
    inStock: true,
    stockCount: 59
  },
  {
    id: "rb-20",
    slug: "perfumed-body-powder-frank-scent-roseberry",
    name: "بودرة برائحة فرانك 200 جم من روز بيري",
    subtitle: "تركيز عالي • جودة معتمدة وتركيبة أصلية 100%",
    description: "نعومة البودرة تلتقي مع رائحة فرانك المحببة في بودرة الجسم برائحة فرانك من روز بيري، لتضيف إلى بشرتكِ انتعاشًا ولمسة عطرية ترافقكِ خلال يومكِ.مواصفات البودرةالنو...",
    badges: ["تركيز عالي"],
    price: {"amount":3.6,"currency":"OMR","compareAtAmount":4.9},
    images: [{"url":"/images/products/rb-20-g1.png","alt":"بودرة برائحة فرانك 200 جم من روز بيري - صورة 1"},{"url":"/images/products/rb-20-g2.png","alt":"بودرة برائحة فرانك 200 جم من روز بيري - صورة 2"},{"url":"/images/products/rb-20-g3.png","alt":"بودرة برائحة فرانك 200 جم من روز بيري - صورة 3"}],
    categories: [category("c-body")],
    brandId: "b-roseberry",
    rating: {"average":4.3,"count":3},
    inStock: true,
    stockCount: 29
  },
  {
    id: "rb-21",
    slug: "laverne-perfumed-body-powder",
    name: "بودرة لافيرن",
    subtitle: "رائحة اللافندر • جودة معتمدة وتركيبة أصلية 100%",
    description: "بودرة لافيرن من أرقى منتجات الجمال المصممة بأعلى معايير الجودة لتمنحكِ إطلالة ساحرة وعناية متكاملة تدوم طويلاً.",
    badges: ["رائحة اللافندر"],
    price: {"amount":3.6,"currency":"OMR","compareAtAmount":5},
    images: [{"url":"/images/products/rb-21-g1.png","alt":"بودرة لافيرن - صورة 1"},{"url":"/images/products/rb-21-g2.png","alt":"بودرة لافيرن - صورة 2"},{"url":"/images/products/rb-21-g3.webp","alt":"بودرة لافيرن - صورة 3"}],
    categories: [category("c-body")],
    brandId: "b-roseberry",
    rating: {"average":4.8999999999999995,"count":296},
    inStock: true,
    stockCount: 79
  },
  {
    id: "rb-22",
    slug: "flora-refined-scented-body-powder",
    name: "بودرة الذوق الرفيع : بودرة  مستوحى من رائحة فلورا",
    subtitle: "مستوحاة من فلورا • جودة معتمدة وتركيبة أصلية 100%",
    description: "إذا كانت الرائحة جزءًا من جمالكِ، فاجعليها تبدأ من روتين جسمكِ؛ بودرة روز بيري برائحة فلورا تمنحكِ لمسة بودرية ناعمة ونفحة عطرية محببة.مواصفات البودرة:النوع: بو...",
    badges: ["مستوحاة من فلورا"],
    price: {"amount":3.6,"currency":"OMR","compareAtAmount":5},
    images: [{"url":"/images/products/rb-22-g1.png","alt":"بودرة الذوق الرفيع : بودرة  مستوحى من رائحة فلورا - صورة 1"},{"url":"/images/products/rb-22-g2.png","alt":"بودرة الذوق الرفيع : بودرة  مستوحى من رائحة فلورا - صورة 2"},{"url":"/images/products/rb-22-g3.png","alt":"بودرة الذوق الرفيع : بودرة  مستوحى من رائحة فلورا - صورة 3"}],
    categories: [category("c-body")],
    brandId: "b-roseberry",
    rating: {"average":4.8999999999999995,"count":146},
    inStock: true,
    stockCount: 36
  },
  {
    id: "rb-23",
    slug: "hydrating-perfumed-body-oil-flora",
    name: "زيت للجسم معطر مستوحى من رائحة فلورا",
    subtitle: "ترطيب مخملي • جودة معتمدة وتركيبة أصلية 100%",
    description: "أفضل زيت جسم معطر مستوحى من فلورا يذوب على بشرتكِ كهمسٍ دافئ، ويتركُ أثر زهري ناعماً يوقظ قلبكِ قبل حواسكِ.مواصفات زيت جسم معطر:النوع: زيت معطر.الاستخدام: الجسم...",
    badges: ["ترطيب مخملي"],
    price: {"amount":3,"currency":"OMR","compareAtAmount":6.1},
    images: [{"url":"/images/products/rb-23-g1.png","alt":"زيت للجسم معطر مستوحى من رائحة فلورا - صورة 1"},{"url":"/images/products/rb-23-g2.png","alt":"زيت للجسم معطر مستوحى من رائحة فلورا - صورة 2"},{"url":"/images/products/rb-23-g3.png","alt":"زيت للجسم معطر مستوحى من رائحة فلورا - صورة 3"}],
    categories: [category("c-body")],
    brandId: "b-magic-skin",
    rating: {"average":4.8,"count":301},
    inStock: true,
    stockCount: 71
  },
  {
    id: "rb-24",
    slug: "sham-perfume-and-khamriya-collection",
    name: "مجموعة شام عطر ومخمرية EAU DE",
    subtitle: "مخمرية شرقية • جودة معتمدة وتركيبة أصلية 100%",
    description: "استمتعي بأفضل تجربة مميزة مع مخمرية للجسم وشام عطر EAU DE عبير يدوم طوال اليوم يبرز أنوثتك ويترك أثر جميل لكل من حولك.مواصفات مخمرية للجسمالنوع: مجموعة عطر شام...",
    badges: ["مخمرية شرقية"],
    price: {"amount":7.2,"currency":"OMR"},
    images: [{"url":"/images/products/rb-24-g1.png","alt":"مجموعة شام عطر ومخمرية EAU DE - صورة 1"},{"url":"/images/products/rb-24-g2.png","alt":"مجموعة شام عطر ومخمرية EAU DE - صورة 2"},{"url":"/images/products/rb-24-g3.png","alt":"مجموعة شام عطر ومخمرية EAU DE - صورة 3"}],
    categories: [category("c-body")],
    brandId: "b-otory",
    rating: {"average":5,"count":1},
    inStock: true,
    stockCount: 83
  },
  {
    id: "rb-25",
    slug: "pomegranate-musk-hair-and-body-khamriya",
    name: "مخمرية مسك برائحة الرمان للشعر والجسم من جولف أوركيد",
    subtitle: "مسك الرمان الشهير • جودة معتمدة وتركيبة أصلية 100%",
    description: "أضيفي مخمرية مسك الرمان إلى روتين العناية اليومي لتنعمي برائحة جسم وشعر منعشة تدوم، بتركيبة خفيفة لطيفة على البشرة والشعر دون جفاف أو تهيج.مواصفات مخمرية مسك ال...",
    badges: ["مسك الرمان الشهير"],
    price: {"amount":5,"currency":"OMR","compareAtAmount":6.6},
    images: [{"url":"/images/products/rb-25-g1.jpg","alt":"مخمرية مسك برائحة الرمان للشعر والجسم من جولف أوركيد - صورة 1"},{"url":"/images/products/rb-25-g2.png","alt":"مخمرية مسك برائحة الرمان للشعر والجسم من جولف أوركيد - صورة 2"},{"url":"/images/products/rb-25-g3.png","alt":"مخمرية مسك برائحة الرمان للشعر والجسم من جولف أوركيد - صورة 3"}],
    categories: [category("c-hair")],
    brandId: "b-golf-orchid",
    rating: {"average":5,"count":3},
    inStock: true,
    stockCount: 86
  },
  {
    id: "rb-26",
    slug: "tropical-fruit-musk-hair-and-body-khamriya",
    name: "مخمرية مسك برائحة الفواكه الاستوائية للشعر والجسم من جولف أوركيد",
    subtitle: "فواكه استوائية • جودة معتمدة وتركيبة أصلية 100%",
    description: "استمتعي بتجربة عطرية مميزة مع مخمرية الجسم والشعر برائحة الفواكه الاستوائية من جولف أوركيد، تمنح نعومة وانتعاش، لإطلالة يومية مفعمة بالحيوية.مواصفات مخمرية الجس...",
    badges: ["فواكه استوائية"],
    price: {"amount":5,"currency":"OMR","compareAtAmount":6.6},
    images: [{"url":"/images/products/rb-26-g1.jpg","alt":"مخمرية مسك برائحة الفواكه الاستوائية للشعر والجسم من جولف أوركيد - صورة 1"},{"url":"/images/products/rb-26-g2.png","alt":"مخمرية مسك برائحة الفواكه الاستوائية للشعر والجسم من جولف أوركيد - صورة 2"},{"url":"/images/products/rb-26-g3.png","alt":"مخمرية مسك برائحة الفواكه الاستوائية للشعر والجسم من جولف أوركيد - صورة 3"}],
    categories: [category("c-hair")],
    brandId: "b-golf-orchid",
    rating: {"average":4.8,"count":375},
    inStock: true,
    stockCount: 27
  },
  {
    id: "rb-27",
    slug: "luxury-hair-mists-heila-beauty",
    name: "معطرات الشعر",
    subtitle: "تعطير ولمعان • جودة معتمدة وتركيبة أصلية 100%",
    description: "معطرات الشعر من أرقى منتجات الجمال المصممة بأعلى معايير الجودة لتمنحكِ إطلالة ساحرة وعناية متكاملة تدوم طويلاً.",
    badges: ["تعطير ولمعان"],
    price: {"amount":4.6,"currency":"OMR","compareAtAmount":6},
    images: [{"url":"/images/products/rb-27-g1.png","alt":"معطرات الشعر - صورة 1"},{"url":"/images/products/rb-27-g2.png","alt":"معطرات الشعر - صورة 2"},{"url":"/images/products/rb-27-g3.webp","alt":"معطرات الشعر - صورة 3"}],
    categories: [category("c-hair")],
    brandId: "b-heila-beauty",
    rating: {"average":4.8999999999999995,"count":85},
    inStock: true,
    stockCount: 92
  },
  {
    id: "rb-28",
    slug: "tahara-musk-4-tola-box-golf-orchid",
    name: "بكج مسك 4 تولات من جولف أوركيد",
    subtitle: "4 تولات مسك • جودة معتمدة وتركيبة أصلية 100%",
    description: "استمتعي برائحة مسك هادئة وثابتة مع بكج مسك الطهارة الاصلي 3 تولات من جولف أوركيد، يمنحك انتعاش وثبات ولمسة عطرية مناسبة للاستخدام اليومي.اختاري بكج مسك 4 تولات...",
    badges: ["4 تولات مسك"],
    price: {"amount":12.1,"currency":"OMR","compareAtAmount":16.2},
    images: [{"url":"/images/products/rb-28-g1.png","alt":"بكج مسك 4 تولات من جولف أوركيد - صورة 1"},{"url":"/images/products/rb-28-g2.jpg","alt":"بكج مسك 4 تولات من جولف أوركيد - صورة 2"},{"url":"/images/products/rb-28-g3.png","alt":"بكج مسك 4 تولات من جولف أوركيد - صورة 3"}],
    categories: [category("c-boxes")],
    brandId: "b-golf-orchid",
    rating: {"average":4.8999999999999995,"count":161},
    inStock: true,
    stockCount: 65
  },
  {
    id: "rb-29",
    slug: "luxury-musk-gift-set-heila-beauty",
    name: "طقم المسك من هيلة بيوتي",
    subtitle: "بوكس إهداء • جودة معتمدة وتركيبة أصلية 100%",
    description: "طقم المسك من هيلة بيوتي من أرقى منتجات الجمال المصممة بأعلى معايير الجودة لتمنحكِ إطلالة ساحرة وعناية متكاملة تدوم طويلاً.",
    badges: ["بوكس إهداء"],
    price: {"amount":12.1,"currency":"OMR","compareAtAmount":16.2},
    images: [{"url":"/images/products/rb-29-g1.png","alt":"طقم المسك من هيلة بيوتي - صورة 1"},{"url":"/images/products/rb-29-g2.png","alt":"طقم المسك من هيلة بيوتي - صورة 2"},{"url":"/images/products/rb-29-g3.webp","alt":"طقم المسك من هيلة بيوتي - صورة 3"}],
    categories: [category("c-boxes")],
    brandId: "b-heila-beauty",
    rating: {"average":4.8999999999999995,"count":242},
    inStock: true,
    stockCount: 47
  },
  {
    id: "rb-30",
    slug: "women-care-intimate-set-y-herb",
    name: "مجموعة العناية النسائية للمناطق الحساسة 5 قطع من واي هيرب",
    subtitle: "عناية طبيعية • جودة معتمدة وتركيبة أصلية 100%",
    description: "لأن العناية بالمنطقة الحساسة تحتاج إلى اختيار منتجات مناسبة لكل خطوة، تأتي مجموعة العناية بالمناطق الحساسة من واي هيرب في روتين واحد عملي وسهل.معلومات المجموعةا...",
    badges: ["عناية طبيعية"],
    price: {"amount":5.2,"currency":"OMR","compareAtAmount":13.8},
    images: [{"url":"/images/products/rb-30-g1.png","alt":"مجموعة العناية النسائية للمناطق الحساسة 5 قطع من واي هيرب - صورة 1"},{"url":"/images/products/rb-30-g2.png","alt":"مجموعة العناية النسائية للمناطق الحساسة 5 قطع من واي هيرب - صورة 2"},{"url":"/images/products/rb-30-g3.png","alt":"مجموعة العناية النسائية للمناطق الحساسة 5 قطع من واي هيرب - صورة 3"}],
    categories: [category("c-boxes")],
    brandId: "b-y-herb",
    rating: {"average":5,"count":9},
    inStock: true,
    stockCount: 57
  },
  {
    id: "rb-31",
    slug: "lip-balm-trio-flavors-roseberry",
    name: "مجموعة ترطيب الشفاه 3 نكهات من روز بيري",
    subtitle: "نكهات طبيعية • جودة معتمدة وتركيبة أصلية 100%",
    description: "دعي شفتيكِ تتنفس الحيوية مع مجموعة معالج الشفاه Lip Therapy من روز بيري (Rose Berry). بوكس مرطب شفايف روز بيري متكامل يجمع لكِ قوة الفازلين النقي (Petroleum Jel...",
    badges: ["نكهات طبيعية"],
    price: {"amount":0.8,"currency":"OMR","compareAtAmount":1.5},
    images: [{"url":"/images/products/rb-31-g1.jpg","alt":"مجموعة ترطيب الشفاه 3 نكهات من روز بيري - صورة 1"},{"url":"/images/products/rb-31-g2.jpg","alt":"مجموعة ترطيب الشفاه 3 نكهات من روز بيري - صورة 2"},{"url":"/images/products/rb-31-g3.png","alt":"مجموعة ترطيب الشفاه 3 نكهات من روز بيري - صورة 3"}],
    categories: [category("c-skincare")],
    brandId: "b-roseberry",
    rating: {"average":4.5,"count":2},
    inStock: true,
    stockCount: 57
  },
  {
    id: "rb-32",
    slug: "mini-perfume-gift-collection-15-pack",
    name: "توزيعات عطور ميني 15 عطر من ميموا",
    subtitle: "ميني فاخر • جودة معتمدة وتركيبة أصلية 100%",
    description: "اجعلى عيدك مميزًا ومليئًا بالبهجة مع توزيعات عطورات ميني ميموا 15 عطر، هدية رائعة تدخل السرور على أحبابك. توزيعات عطور ميني فريدة تجمع بين الأناقة والرائحة الرا...",
    badges: ["ميني فاخر"],
    price: {"amount":20.3,"currency":"OMR"},
    images: [{"url":"/images/products/rb-32-g1.png","alt":"توزيعات عطور ميني 15 عطر من ميموا - صورة 1"},{"url":"/images/products/rb-32-g2.jpg","alt":"توزيعات عطور ميني 15 عطر من ميموا - صورة 2"},{"url":"/images/products/rb-32-g3.png","alt":"توزيعات عطور ميني 15 عطر من ميموا - صورة 3"}],
    categories: [category("c-boxes")],
    brandId: "b-roseberry",
    rating: {"average":5,"count":4},
    inStock: true,
    stockCount: 50
  },
  {
    id: "rb-elec-1",
    slug: "professional-2in1-ionic-hair-styler",
    name: "مصفف ومجفف الشعر الاحترافي 2 في 1 بالأيونات السالبة",
    subtitle: "حائز على أعلى تقييم • ضمان سنتين معتمد",
    description: "جهاز تصفيف وتجفيف احترافي بقوة 1200 واط مع تقنية الأيونات السالبة لمنع الهيشان ومنح الشعر نعومة ولمعاناً فائقاً بحركة واحدة سلسة.",
    badges: ["الأكثر طلباً","ضمان سنتين"],
    price: {"amount":18.5,"currency":"OMR","compareAtAmount":26},
    images: [{"url":"/images/categories/electronics.webp","alt":"مصفف ومجفف الشعر الاحترافي 2 في 1 بالأيونات السالبة"}],
    categories: [category("c-electronics")],
    brandId: "b-roseberry",
    rating: {"average":4.9,"count":340},
    inStock: true,
    stockCount: 45
  },
  {
    id: "rb-elec-2",
    slug: "ultrasonic-deep-skin-scrubber-peeling",
    name: "جهاز تنظيف وتقشير البشرة بالموجات فوق الصوتية",
    subtitle: "تنظيف مسام احترافي بالمنزل • شحن USB سريع",
    description: "جهاز إزالة الرؤوس السوداء وتنظيف المسام العميق بالموجات فوق الصوتية مع وضع التدليك وامتصاص السيرومات بفعالية مضاعفة.",
    badges: ["ترند العناية","نتائج فورية"],
    price: {"amount":14.9,"currency":"OMR","compareAtAmount":21},
    images: [{"url":"/images/categories/skincare.webp","alt":"جهاز تنظيف وتقشير البشرة بالموجات فوق الصوتية"}],
    categories: [category("c-electronics")],
    brandId: "b-magic-skin",
    rating: {"average":4.8,"count":195},
    inStock: true,
    stockCount: 30
  },
  {
    id: "rb-elec-3",
    slug: "ceramic-thermal-straightening-brush",
    name: "فرشاة فرد وتمليس الشعر الحرارية بسيراميك التورمالين",
    subtitle: "فرد فوري وسلس لجميع أنواع الشعر • حماية من الحرارة",
    description: "فرشاة تمليس سريعة التسخين بحرارة قابلة للتعديل حتى 230 درجة مئوية مع حماية متطورة من الحروق وتوزيع متساوٍ للحرارة.",
    badges: ["توفير الوقت","حماية متطورة"],
    price: {"amount":16.5,"currency":"OMR","compareAtAmount":23.5},
    images: [{"url":"/images/categories/haircare.webp","alt":"فرشاة فرد وتمليس الشعر الحرارية بسيراميك التورمالين"}],
    categories: [category("c-electronics")],
    brandId: "b-roseberry",
    rating: {"average":4.9,"count":210},
    inStock: true,
    stockCount: 50
  },
  {
    id: "rb-elec-4",
    slug: "led-facial-massager-ems-therapy",
    name: "جهاز شد وتدليك الوجه والرقبة بالعلاج الضوئي LED وموجات EMS",
    subtitle: "نضارة وشد للبشرة بالمنزل • تصميم مريح وانسيابي",
    description: "تقنية مبتكرة لمكافحة علامات التقدم بالسن وشد بشرة الوجه والرقبة من خلال التحفيز العضلي EMS والأضواء العلاجية (الأحمر، الأزرق، والأخضر).",
    badges: ["ابتكار عالمي","نضارة فورية"],
    price: {"amount":19.9,"currency":"OMR","compareAtAmount":28},
    images: [{"url":"/images/categories/summer.webp","alt":"جهاز شد وتدليك الوجه والرقبة بالعلاج الضوئي LED وموجات EMS"}],
    categories: [category("c-electronics")],
    brandId: "b-magic-skin",
    rating: {"average":4.8,"count":160},
    inStock: true,
    stockCount: 22
  }
]

export const mockCollections: Collection[] = [
  {
    "id": "col-best-deals",
    "slug": "flash-deals",
    "name": "عروض وصفقات حصرية",
    "description": "أقوى التخفيضات والصفقات على باقة من أفضل المنتجات المختارة.",
    "kind": "seasonal",
    "productIds": [
      "rb-1",
      "rb-2",
      "rb-3",
      "rb-4",
      "rb-5",
      "rb-6",
      "rb-7",
      "rb-8",
      "rb-9",
      "rb-10"
    ]
  },
  {
    "id": "col-boxes",
    "slug": "luxury-boxes",
    "name": "بوكسات الجمال والهدايا الفاخرة",
    "description": "أروع المجموعات المتكاملة وبكجات المسك والعطور للإهداء والاستخدام الشخصي.",
    "kind": "editorial",
    "productIds": [
      "rb-1",
      "rb-28",
      "rb-29",
      "rb-30",
      "rb-32"
    ]
  },
  {
    "id": "col-electronics",
    "slug": "beauty-devices",
    "name": "أجهزة التجميل والتصفيف",
    "description": "أحدث التقنيات وأجهزة تصفيف الشعر والعناية بالبشرة بأعلى معايير الأمان والفعالية.",
    "kind": "editorial",
    "productIds": [
      "rb-elec-1",
      "rb-elec-2",
      "rb-elec-3",
      "rb-elec-4"
    ]
  },
  {
    "id": "col-fragrance-hair",
    "slug": "fragrance-hair",
    "name": "عطور ومخمريات الشعر والجسم",
    "description": "روائح فواحة وثابتة تأسر الحواس طوال اليوم.",
    "kind": "regional",
    "productIds": [
      "rb-12",
      "rb-13",
      "rb-14",
      "rb-15",
      "rb-16",
      "rb-17",
      "rb-18",
      "rb-19",
      "rb-25",
      "rb-26"
    ]
  }
]
